password: "example"
server: "irc.example.com"
channel: "#example"
git_work_dir: "./"
pull_request_comment: "example"
mirage_url: "http://example.com"
docker_image: "example:master"
after_image: "example.png"